CN-12
VeamVeat/python-practice pull request #1
Opened 2021-09-24 18:14 UTC by VeamVeat

https://trello.com/c/8rBnXpgX

2021-10-06 10:28 UTC, VeamVeat commented on python_fundamentals/string_to_Int.py
> +s_input = input()
Исправлено

2021-10-06 10:29 UTC, VeamVeat commented on python_fundamentals/string_to_Int.py
> +class DataValidException(Exception):
Исправлено

2021-10-06 10:29 UTC, VeamVeat commented on python_fundamentals/string_to_Int.py
> +        for id_i, i in enumerate(string):
Исправлено

2021-10-06 10:29 UTC, VeamVeat commented on python_fundamentals/string_to_Int.py
> +s = str_to_int(s_input)
Исправлено

2021-10-07 07:21 UTC, MyNameIsVladislav commented on python_fundamentals/string_to_Int.py
> +
Принято, хотя некоторые имена переменных звучат странно, передаю Максу

2021-10-17 18:31 UTC, MaxKomarenko requested changes

2021-10-17 18:31 UTC, MaxKomarenko commented on python_fundamentals/string_to_Int.py
> +        str_number = [f'{i}' for i in range(10)]
f'{i}' почему не использовать str()? Что будет если число знаков будет больше 10?

2021-10-17 18:31 UTC, MaxKomarenko commented on python_fundamentals/string_to_Int.py
> +        str_number = [f'{i}' for i in range(10)]
Вложенные циклы это долго. Нужно найти более быстрый способ

2021-10-17 18:31 UTC, MaxKomarenko commented on python_fundamentals/string_to_Int.py
> +        for user_index_in_string, user_symbol_in_string in enumerate(user_string):
user_index_in_string - индекс пользователя в строке, так и планировалось?

2021-10-17 18:31 UTC, MaxKomarenko commented on python_fundamentals/string_to_Int.py
> +            for index_in_str_number, symbol_in_str_number in enumerate(str_number):
index_in_str_number - индекс в строке числа?

2021-10-17 18:31 UTC, MaxKomarenko commented on python_fundamentals/string_to_Int.py
> +            for index_in_str_number, symbol_in_str_number in enumerate(str_number):
symbol_in_str_number - символ в строке числа?

2021-10-17 18:31 UTC, MaxKomarenko commented on python_fundamentals/string_to_Int.py
> +        str_number = [f'{i}' for i in range(10)]
str_number - строка число?

2021-10-17 18:31 UTC, MaxKomarenko commented on python_fundamentals/string_to_Int.py
> +                if symbol_in_str_number == user_symbol_in_string and user_index_in_string == len(user_string) - 1:
Нэйминг в этой строке очень сильно усложняет процесс понимания того, что здесь происходит. А еще, какя длина строки?

2021-10-17 18:31 UTC, MaxKomarenko commented on python_fundamentals/string_to_Int.py
> +                    result_list.append(index_in_str_number * 10 ** (len(user_string) - 1 - user_index_in_string))
Какая максимальная длина строки?

2021-10-17 18:31 UTC, MaxKomarenko commented on python_fundamentals/string_to_Int.py
> +                    result_list.append(index_in_str_number * 10 ** (len(user_string) - 1 - user_index_in_string))
10 - магическое число, непонятно какую роль оно тут играет. Нужно стараться избегать магических чисел и создавать переменные которым присваивать числа. По названию переменной будет ясно, что это и зачем.

2021-10-17 18:31 UTC, MaxKomarenko commented on python_fundamentals/string_to_Int.py
> +    return sum(result_list) if user_string[0] != '-' else sum(result_list) * -1
user_string[0] - а если строка пустая?

2021-10-18 09:56 UTC, VeamVeat commented on python_fundamentals/string_to_Int.py
> +    return sum(result_list) if user_string[0] != '-' else sum(result_list) * -1
выбросит исключение

2022-10-25 09:42 UTC, merged