CN-13
VeamVeat/python-practice pull request #2
Opened 2021-09-25 09:51 UTC by VeamVeat

https://trello.com/c/EAhQM3t4

2021-10-07 07:24 UTC, MyNameIsVladislav commented on python_fundamentals/max_long_period_of_time.py
> +    return max(time_hour_minute_second, key=time_hour_minute_second.get)
Можно было назвать просто max_time :D

2021-10-17 18:19 UTC, MaxKomarenko requested changes

2021-10-17 18:19 UTC, MaxKomarenko commented on python_fundamentals/max_long_period_of_time.py
> +    time_hour_minute_second = {
Плохой нейминг. Ты описал, что хранится в переменной и описал, что будет храниться. Но не описываешь ее предназначение. Убери hour minute seconds

2021-10-17 18:19 UTC, MaxKomarenko commented on python_fundamentals/max_long_period_of_time.py
> +        f'{h}': h * 3600,
Зачем здесь преобразование в строку? Почему не использовать str() ? Или не оставить число? Отвечать нужно на все три вопроса

2022-10-25 09:40 UTC, merged